export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL';

export const FETCH_JOB_REQUEST = 'FETCH_JOB_REQUEST';
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS';
export const FETCH_JOB_FAIL = 'FETCH_JOB_FAIL';

export const POST_DOCUMENT_PARSING_REQUEST = 'POST_DOCUMENT_PARSING_REQUEST';
export const POST_DOCUMENT_PARSING_SUCCESS = 'POST_DOCUMENT_PARSING_SUCCESS';
export const POST_DOCUMENT_PARSING_FAIL = 'POST_DOCUMENT_PARSING_FAIL';

export const POST_DOCUMENT_REVEALING_REQUEST = 'POST_DOCUMENT_REVEALING_REQUEST';
export const POST_DOCUMENT_REVEALING_SUCCESS = 'POST_DOCUMENT_REVEALING_SUCCESS';
export const POST_DOCUMENT_REVEALING_FAIL = 'POST_DOCUMENT_REVEALING_FAIL';

export const ADD_PROFILE_REQUEST = 'ADD_PROFILE_REQUEST';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_FAIL = 'ADD_PROFILE_FAIL';

export const PUT_PROFILE_REQUEST = 'PUT_PROFILE_REQUEST';
export const PUT_PROFILE_SUCCESS = 'PUT_PROFILE_SUCCESS';
export const PUT_PROFILE_FAIL = 'PUT_PROFILE_FAIL';

export const EDIT_PROFILE_CONSENT_REQUEST = 'EDIT_PROFILE_CONSENT_REQUEST';
export const EDIT_PROFILE_CONSENT_SUCCESS = 'EDIT_PROFILE_CONSENT_SUCCESS';
export const EDIT_PROFILE_CONSENT_FAIL = 'EDIT_PROFILE_CONSENT_FAIL';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const  UPDATE_BOARD_FILTERS = 'UPDATE_BOARD_FILTERS';

export const REMOVE_PROFILE = 'REMOVE_PROFILE'